name: Publish technoblog on gh-pages
on: [push]

jobs:
    publish:
        runs-on: ubuntu-18.04
        steps:
            # Make files accessible to actions
            # https://github.com/actions/checkout#readme
            - uses: actions/checkout@v2
          
            # Install Node
            # https://github.com/actions/setup-node#readme
            - name: Install Node and dependencies
              uses: actions/setup-node@v1
              with:
                node-version: 12.x
            # Install dependencies
            - run: npm ci
            # Build eventy with prefixurl
            - name: Build Eventy
              run: npx @11ty/eleventy --pathprefix='/techblog/'
            - name: Deploy on gh-pages
              run: | 
                echo 'Cloning gh-pages' 
                git clone -b gh-pages "https://$GITHUB_TOKEN@github.com/leancoder23/techblog.git" gh-pages
                tree gh-pages
                rm -rf gh-pages/*
                echo 'After remove'
                tree gh-pages
                cp -r _site/* gh-pages
                echo 'After Copy'
                tree gh-pages
                cd gh-pages
                git push
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

              #uses: peaceiris/actions-gh-pages@v1.1.0
              #env:
              #  PUBLISH_DIR: _site 
              #  PUBLISH_BRANCH: gh-pages
              #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
