name: Publish technoblog on gh-pages
on: [push]

jobs:
    publish:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@master
            - name: Build
                runs: 
                    using: 'docker'
                    image: 'Dockerfile'
            - name: Deploy
                uses: peaceiris/actions-gh-pages@v1.1.0
                env:
                PUBLISH_DIR: _site 
                PUBLISH_BRANCH: gh-pages
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
