name: Publish technoblog on gh-pages
on: [push]

jobs:
    publish:
        runs-on: ubuntu-18.04
        steps:
            # Make files accessible to actions
            # https://github.com/actions/checkout#readme
            - uses: actions/checkout@v2
            - name: Install Node and dependencies
            # Install Node
            # https://github.com/actions/setup-node#readme
            - uses: actions/setup-node@v1
              with:
                node-version: 12.x
            # Install dependencies
            - run: npm ci
            # Build eventy with prefixurl
            - name: Build Eventy
            - run: npx @11ty/eleventy --pathprefix='/techblog/'
            - name: Deploy on gh-pages
              uses: peaceiris/actions-gh-pages@v1.1.0
              env:
                PUBLISH_DIR: _site 
                PUBLISH_BRANCH: gh-pages
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
