name: Publish technoblog on gh-pages
on: [push]

jobs:
    publish:
        runs-on: ubuntu-18.04
        steps:
            # Make files accessible to actions
            # https://github.com/actions/checkout#readme
            - uses: actions/checkout@v2
          
            # Install Node
            # https://github.com/actions/setup-node#readme
            - name: Install Node and dependencies
              uses: actions/setup-node@v1
              with:
                node-version: 12.x
            # Install dependencies
            - run: npm ci
            # Build eventy with prefixurl
            - name: Build Eventy
              run: npx @11ty/eleventy --pathprefix='/techblog/'
            - name: Deploy on gh-pages
              run: |  
                echo 'DS test'
                echo 'git user name : ${{GITHUB_USER}}, token : ${{ secrets.GITHUB_TOKEN }}'
                git config --global user.name 'leancoder23'
                git config --global user.email 'leancoder23@users.noreply.github.com'
                npx gh-pages -d _site -r https://github.com/leancoder23/techblog.git
              env:
                GITHUB_USER: ${{ github.event.schedule.user.login }}

              #uses: peaceiris/actions-gh-pages@v1.1.0
              #env:
              #  PUBLISH_DIR: _site 
              #  PUBLISH_BRANCH: gh-pages
              #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
